class ATM :
    Bank_Name="SBI"
    min_blnc=500
    pin=1234
    def__init__(self,Ac no,name,u_pin,blnc)
    {
        self.ac no = ac no;
        self.name = Name
        self.u_pin = u_pin
        self.blnc = blnc
    }
    def withdraw(self)
        w_amount = int(input("enter withdraw amount"))
        if(w_amt_self.blnc)
        self.blnc = self.blnc_want
    else:
in.blnc
def.deposit(self)
d_amt= int(input("enter deposite amount"))
self.blnc_self.blnc+d_amt

def menu(self)
    print("welcome")
    choice = int(input("enter your choice"))

    if choice==1:
    self.with()
elif ch==2:
self.dep()
elif ch==3:
self.check()
elif